export default function M1View({ content }) {
  return (
    <div className="flex flex-col h-full bg-[#0B0C10] text-[#C5C6C7] rounded-b-2xl">
      <div className="px-6 py-4 border-b border-white/5 bg-[#1F2833]/50">
        <h3 className="font-semibold text-brand-light flex items-center gap-2">
          Folder Structure Explanation
        </h3>
        <p className="text-sm text-brand-light/60 mt-1">Generated by AI based on repository contents</p>
      </div>
      <div className="flex-1 p-6 overflow-auto custom-scrollbar">
        {content ? (
          <pre className="text-[14px] font-mono leading-relaxed bg-transparent whitespace-pre-wrap">
            {content}
          </pre>
        ) : (
          <div className="flex items-center justify-center h-full text-brand-light/30">
            No folder structure data available
          </div>
        )}
      </div>
    </div>
  );
}
